policycoreutils/gui: Fix portsPage in system-config-selinux
Commit af59544e accidentally removed columns definition from
portsPage.py. This commit reverts it.

Fixes:
$ sudo system-config-selinux
/usr/share/system-config-selinux/system-config-selinux.py:80: Warning: g_object_get_valist: object class 'GnomeProgram' has no property named 'default-icon'
  xml = gtk.glade.XML("/usr/share/system-config-selinux/system-config-selinux.glade", domain=PROGNAME)
Traceback (most recent call last):
  File "/usr/share/system-config-selinux/system-config-selinux.py", line 197, in <module>
    app = childWindow()
  File "/usr/share/system-config-selinux/system-config-selinux.py", line 100, in __init__
    self.add_page(portsPage.portsPage(xml))
  File "/usr/share/system-config-selinux/portsPage.py", line 74, in __init__
    self.init_store()
  File "/usr/share/system-config-selinux/portsPage.py", line 92, in init_store
    col = gtk.TreeViewColumn(_("SELinux Port\nType"), gtk.CellRendererText(), text=TYPE_COL)
NameError: global name 'TYPE_COL' is not defined

Signed-off-by: Petr Lautrbach <plautrba@redhat.com>